/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Balo;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class KetNoiCSDL extends javax.swing.JFrame {

    /**
     * Creates new form KetNoiCSDL
     */
    public KetNoiCSDL() {
        initComponents();
        this.setSize(500, 300);
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("NHẬP THÔNG TIN");
    }
    private int loi = 0;
    static Connection conn;
    public Connection connectMySql(String tendangnhap, String matkhau) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/nienluan?useUnicode=true&characterEncoding=UTF-8", tendangnhap, matkhau);
            loi = 1;
            return conn;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng!");
            System.out.print("connect failure!!!" + ex);
            loi = 0;
        }
        return null;
    }
    
    public void connect(String tdn, String mk) {
        if (!tdn.equals("")) {
            conn = connectMySql(tdn, mk);
            if (loi == 1) {
                GiaoDienChinh gD = new GiaoDienChinh();
                PrintWriter pw;
                try {
                    pw = new PrintWriter(new File(gD.tenFile));
                    System.out.print(gD.tenFile);
                    pw.println(tdn);
                    pw.printf(mk);

                    pw.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(KetNoiCSDL.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTTenDangNhap = new javax.swing.JTextField();
        jTMatKhau = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 100, 120, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 150, 80, 17);
        getContentPane().add(jTTenDangNhap);
        jTTenDangNhap.setBounds(200, 100, 216, 30);
        getContentPane().add(jTMatKhau);
        jTMatKhau.setBounds(200, 140, 216, 30);

        jButton1.setBackground(new java.awt.Color(155, 151, 84));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("KẾT NỐI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 200, 130, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VUI LÒNG NHẬP THÔNG TIN ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 20, 210, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HỆ QUẢN TRỊ CSDL MYSQL CỦA BẠN ĐỀ KẾT NỐI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 50, 350, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Balo/background-nho.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-9, -4, 510, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        connect(jTTenDangNhap.getText(), jTMatKhau.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetNoiCSDL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetNoiCSDL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetNoiCSDL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetNoiCSDL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KetNoiCSDL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTMatKhau;
    private javax.swing.JTextField jTTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
