/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Balo;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class XuatFileKetQua extends javax.swing.JFrame {
    
    private Connection conn;
    private String tenFile, noiLuuFile, tentt;
    static Balo balo;
    public XuatFileKetQua() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("XUẤT FILE KẾT QUẢ");
       
        KetNoiCSDL ketNoiCSDL = new KetNoiCSDL();
        conn = ketNoiCSDL.conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTNoiLuuFile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBXuatFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTTenFile = new javax.swing.JTextField();
        jCMoRong = new javax.swing.JComboBox();
        jBThoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);
        jPanel1.add(jTNoiLuuFile);
        jTNoiLuuFile.setBounds(110, 120, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nơi lưu:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 130, 54, 17);

        jBXuatFile.setBackground(new java.awt.Color(155, 151, 84));
        jBXuatFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBXuatFile.setText("XUẤT FILE");
        jBXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXuatFileActionPerformed(evt);
            }
        });
        jPanel1.add(jBXuatFile);
        jBXuatFile.setBounds(110, 170, 120, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tên file:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 54, 17);
        jPanel1.add(jTTenFile);
        jTTenFile.setBounds(110, 80, 260, 30);

        jCMoRong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".txt", ".inp", ".docx", ".doc" }));
        jPanel1.add(jCMoRong);
        jCMoRong.setBounds(380, 80, 70, 30);

        jBThoat.setBackground(new java.awt.Color(155, 151, 84));
        jBThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBThoat.setText("THOÁT");
        jBThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThoatActionPerformed(evt);
            }
        });
        jPanel1.add(jBThoat);
        jBThoat.setBounds(259, 170, 110, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Balo/background.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 0, 540, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void ghiDuLieu(Balo bl, String duongdan) {
        try {
            File tenfile = new File(duongdan);
            if (tenfile.exists()) {
                JOptionPane.showMessageDialog(this, "File này đã tồn tại!");
            } else {
                Writer out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(tenfile), "UTF8"));
                ArrayList <DoVat> dsDV = new ArrayList<>(bl.getListDV());

                out.append("Thuật toán: " +  tentt).append("\r\n");
                out.append("Loại balo: " + bl.getLoai()).append("\r\n");
                out.append("Khối lượng balo: " + bl.getKhoiLuongBL()).append("\r\n");

                if (bl.getLoai() == 1) {
                    out.append("STT \t Khối lượng \t Giá trị \t Đơn giá \t Phương án \t  Tên").append("\r\n");
                    for (DoVat dv : dsDV) {
                        double dgia = (double)Math.round(dv.getDGia()*1000)/1000;
                        out.append(dv.getSTT()  + " \t  " + dv.getKLuong() + " \t\t " + dv.getGTri() + " \t \t   " + dgia + " \t \t " + dv.getPAn() + "\t\t " + dv.getTen()).append("\r\n");
                    }

                } else {
                    out.append("STT \t Khối lượng \t Giá trị \t Đơn giá \t Số lượng \t Phương án \t  Tên").append("\r\n");
                    for (DoVat dv : dsDV) {
                        double dgia = (double)Math.round(dv.getDGia()*1000)/1000;
                        out.append(dv.getSTT()  + " \t  " + dv.getKLuong() + " \t\t " + dv.getGTri() + " \t \t  " + dgia + " \t\t " + dv.getSoLuong() + " \t\t  " + dv.getPAn() + "\t\t " + dv.getTen()).append("\r\n");
                    }
                }
                out.flush();
                out.close();

                JOptionPane.showMessageDialog(this, "Xuất file kết quả thành công!!!");
                this.setVisible(false);
            }
        } catch (UnsupportedEncodingException e) {
            JOptionPane.showMessageDialog(this, "Nơi lưu file không tồn tại!");
            System.out.println(e.getMessage());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Nơi lưu file không tồn tại!");
            System.out.println(e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nơi lưu file không tồn tại!");
            System.out.println(e.getMessage());
        }
    }
    
    private void jBXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXuatFileActionPerformed
        if (jTTenFile.getText().equals("") || jTNoiLuuFile.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
        } else {
            
            tenFile = new String(jTTenFile.getText());
            noiLuuFile = new String(jTNoiLuuFile.getText());
            PhuongPhapGiai thuatToan = new PhuongPhapGiai();
            
            balo = new Balo(thuatToan.balo);
            
            System.out.print(balo.getKhoiLuongBL());
            ghiDuLieu(balo, noiLuuFile + "/" + tenFile + jCMoRong.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_jBXuatFileActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PhuongPhapGiai tt = new PhuongPhapGiai();
        tentt = new String(tt.ttt);
    }//GEN-LAST:event_formWindowOpened

    private void jBThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatFileKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatFileKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatFileKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatFileKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatFileKetQua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBThoat;
    private javax.swing.JButton jBXuatFile;
    private javax.swing.JComboBox jCMoRong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNoiLuuFile;
    private javax.swing.JTextField jTTenFile;
    // End of variables declaration//GEN-END:variables
}
