/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nien_luan;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author longs
 */
public class DS_Balo extends javax.swing.JFrame {

    /**
     * Creates new form DS_Balo
     */
    public DS_Balo() {
        initComponents();
        this.setSize(850, 550);
        this.showBalo();
        this.resetButton(true);
        this.resetview();
        this.setLocation(960 - this.getSize().width / 2, 300);
    }

    public int getloai(){
        int i = 0;
        if(rdbLoai1.isSelected())
            i = 1;
        if(rdbLoai2.isSelected())
            i = 2;
        if(rdbLoai3.isSelected())
            i = 3;
        return i;
    }
    
    static Balo balo;
    private int id;
    private int sluong;
    //Chức Năng Của from
    
    //Thêm Cái Balo vào MySQL
    public void themBalo(){
        try {
            ClsDatabase.open();
            String sql = new String("insert into balo(mso, kluong, loai, soluongdv) values (?,?,?,?)");
            PreparedStatement ps = ClsDatabase.con.prepareCall(sql);
            
            ps.setString(1, txtMSBalo.getText());
            ps.setFloat(2, Float.parseFloat(txtTKLuong.getText()));
            ps.setInt(3, getloai());
            ps.setInt(4, 0);
            
            ps.executeUpdate();
            ClsDatabase.close();
            JOptionPane.showMessageDialog(this, "Thêm balo thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Hiển thị tất cả Balo
    public void showBalo(){
        DefaultTableModel tblModel = (DefaultTableModel) tableDS_Balo.getModel();
        tblModel.setRowCount(0);//reset view jtable
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select * from balo");
            while (rs.next()) {
                String id = rs.getString(1);
                String maso = rs.getString(2);
                String diemS = rs.getString(3);
                String loai = rs.getString(4);
                String soluongdv = rs.getString(5);

                String Data[] = {id, maso, diemS, loai, soluongdv};
                tblModel.addRow(Data);
            }
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Cập nhập Balo
    public void updateBalo(){
        try {
            ClsDatabase.open();
            String url = "update balo set mso = ?, kluong = ?, loai = ? where id = ? ";
            PreparedStatement ps = ClsDatabase.con.prepareStatement(url);
            
            ps.setString(1, txtMSBalo.getText());
            ps.setFloat(2, Float.parseFloat(txtTKLuong.getText()));
            ps.setInt(3, getloai());
            ps.setInt(4, this.id);
            
            ps.executeUpdate();
            ClsDatabase.close();
            JOptionPane.showMessageDialog(this, "Cập nhật balo thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Reset button
    public void resetButton(Boolean k){
        btnLuu.setEnabled(k);
        btnCapNhat.setEnabled(!k);
        btnXoa.setEnabled(!k);
        btnThemDoVat.setEnabled(!k);
        btnThoatToan.setEnabled(!k);
    }
    
    //Reset view
    public void resetview(){
        this.id = 0;
        txtMSBalo.setText("");
        txtTKLuong.setText("");
        rdbLoai1.setSelected(true);
    }
    
    //Xoa Balo
    public void XoaBalo(){
        try {
            ClsDatabase.open();
            String url = "delete from balo where id = ?";
            PreparedStatement ps = ClsDatabase.con.prepareStatement(url);
            
            ps.setInt(1, this.id);
            ps.executeUpdate();
            ClsDatabase.close();
            JOptionPane.showMessageDialog(this, "Xóa balo thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDS_Balo = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMSBalo = new javax.swing.JTextField();
        txtTKLuong = new javax.swing.JTextField();
        rdbLoai1 = new javax.swing.JRadioButton();
        rdbLoai2 = new javax.swing.JRadioButton();
        rdbLoai3 = new javax.swing.JRadioButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnThoatToan = new javax.swing.JButton();
        btnThemDoVat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh Sách Balo");
        setSize(new java.awt.Dimension(850, 550));

        tableDS_Balo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Số", "Khối Lượng", "Loại", "Số Đồ Vật"
            }
        ));
        tableDS_Balo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDS_BaloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDS_Balo);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Danh Sách Balo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã số balo :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tổng khối lượng :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Loại :");

        buttonGroup1.add(rdbLoai1);
        rdbLoai1.setText("Loại 1");

        buttonGroup1.add(rdbLoai2);
        rdbLoai2.setText("Loại 2");

        buttonGroup1.add(rdbLoai3);
        rdbLoai3.setText("Loại 3");

        btnLuu.setText("Lưu Balo");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật Balo");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa Balo");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnThoatToan.setText("Chọn Thuật Toán");
        btnThoatToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatToanActionPerformed(evt);
            }
        });

        btnThemDoVat.setText("Thêm Đồ Vật");
        btnThemDoVat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDoVatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMSBalo)
                                    .addComponent(txtTKLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(rdbLoai1)
                                .addGap(54, 54, 54)
                                .addComponent(rdbLoai2)
                                .addGap(56, 56, 56)
                                .addComponent(rdbLoai3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThoatToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemDoVat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMSBalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTKLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbLoai1)
                    .addComponent(rdbLoai2)
                    .addComponent(rdbLoai3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapNhat)
                            .addComponent(btnXoa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThoatToan)
                            .addComponent(btnThemDoVat)
                            .addComponent(btnQuayLai)))
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        this.themBalo();
        this.showBalo();
        this.resetview();
        this.resetButton(true);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        this.updateBalo();
        this.showBalo();
        this.resetview();
        this.resetButton(true);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tableDS_BaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDS_BaloMouseClicked
        // TODO add your handling code here:
        int row = tableDS_Balo.getSelectedRow();
        TableModel model = tableDS_Balo.getModel();
        
        this.id = Integer.parseInt(model.getValueAt(row, 0).toString());
        txtMSBalo.setText(model.getValueAt(row, 1).toString());
        txtTKLuong.setText(model.getValueAt(row, 2).toString());
        int loai = Integer.parseInt(model.getValueAt(row, 3).toString());
        if(loai == 1)
            rdbLoai1.setSelected(true);
        if(loai == 2)
            rdbLoai2.setSelected(true);
        if(loai == 3)
            rdbLoai3.setSelected(true);
        this.sluong = Integer.parseInt(model.getValueAt(row, 4).toString());
        this.resetButton(false);
    }//GEN-LAST:event_tableDS_BaloMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.XoaBalo();
        this.showBalo();
        this.resetview();
        this.resetButton(true);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemDoVatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDoVatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DS_DoVat g = new DS_DoVat(this.id, txtMSBalo.getText(), Float.parseFloat(txtTKLuong.getText()), getloai());
        g.setVisible(true);
    }//GEN-LAST:event_btnThemDoVatActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThoatToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatToanActionPerformed
        this.setVisible(false);
        Thuat_Toan t = new Thuat_Toan(txtMSBalo.getText(),Float.parseFloat(txtTKLuong.getText()),getloai(),this.sluong, this.id);
        t.setVisible(true);
    }//GEN-LAST:event_btnThoatToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DS_Balo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DS_Balo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DS_Balo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DS_Balo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DS_Balo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThemDoVat;
    private javax.swing.JButton btnThoatToan;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdbLoai1;
    private javax.swing.JRadioButton rdbLoai2;
    private javax.swing.JRadioButton rdbLoai3;
    private javax.swing.JTable tableDS_Balo;
    private javax.swing.JTextField txtMSBalo;
    private javax.swing.JTextField txtTKLuong;
    // End of variables declaration//GEN-END:variables
}
