/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nien_luan;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author longs
 */
public class Tat_Ca_Thuat_Toan extends javax.swing.JFrame {

    /**
     * Creates new form Tat_Ca_Thuat_Toan
     */
    public Tat_Ca_Thuat_Toan() {
        initComponents();
    }
    public Tat_Ca_Thuat_Toan(Balo balo,float khoiLuongMacDinh) {
        initComponents();
        this.setLocation(960 - this.getSize().width / 2, 300);
        baloThamAn = new Balo(balo);
        baloNhanhCan = new Balo(balo);
        baloQuyHoanhDong = new Balo(balo);
        this.khoiLuongMacDinh = khoiLuongMacDinh;
        Show();
//        System.out.println(baloThamAn.getDv()[0].getTen());
    }
    private Balo baloThamAn;
    private Balo baloNhanhCan;
    private Balo baloQuyHoanhDong;
    private float khoiLuongMacDinh;
    public void Show(){
        baloThamAn.Greedy();
        showDoVat(baloThamAn, tableDoVatThamAn);
        labelChuaDuocThamAn.setText(baloThamAn.khoiLuongCoTrongBalo()+"");
        labelGiaTriThamAn.setText(baloThamAn.tongGiaTri()+"");
        labelKLDuThamAn.setText(khoiLuongMacDinh - baloThamAn.khoiLuongCoTrongBalo() + "");
        
        baloNhanhCan.TaoNutGoc();
        baloNhanhCan.BranchAndBound(0);
        showDoVat(baloNhanhCan, tableDoVatNhanhCan);
        labelChuaDuocNhanhCan.setText(baloNhanhCan.khoiLuongCoTrongBalo()+"");
        labelGiaTriNhanhCan.setText(baloNhanhCan.tongGiaTri()+"");
        labelKLDuNhanhCan.setText(khoiLuongMacDinh - baloNhanhCan.khoiLuongCoTrongBalo() + "");
        
        baloQuyHoanhDong.SapXepSTT(baloQuyHoanhDong.getDv(), baloQuyHoanhDong.getSoluongdv());
        baloQuyHoanhDong.TaoBang();
        baloQuyHoanhDong.TraBang();
        showDoVat(baloQuyHoanhDong, tableDoVatQuyHoanhDong);
        labelChuaDuocQuyHoanhDong.setText(baloQuyHoanhDong.khoiLuongCoTrongBalo()+"");
        labelGiaTriQuyHoanhDong.setText(baloQuyHoanhDong.tongGiaTri()+"");
        labelKLDuQuyHoanhDong.setText(khoiLuongMacDinh - baloQuyHoanhDong.khoiLuongCoTrongBalo() + "");
        
        //Thuật Toán Tối ưu
        int x = (int) max(baloThamAn.tongGiaTri(),baloNhanhCan.tongGiaTri(),baloQuyHoanhDong.tongGiaTri());
        System.out.println(x);
        if(x == 1){
            ToiUu.setText("Tham Ăn");
        }
        if(x == 2){
            ToiUu.setText("Nhanh Cận");
        }
        if(x == 3){
            ToiUu.setText("Quy Hoạnh Động");
        }
    }
        //Hiển thị tất cả đồ vật
    public void showDoVat(Balo balo,JTable s){
        DefaultTableModel tblModel = (DefaultTableModel) s.getModel();
        tblModel.setRowCount(0);//reset view jtable
        try {
            for (int i = 0; i < balo.getSoluongdv(); i++) {
                String tendv = balo.getDv()[i].getTen();;
                String soluong = String.valueOf(balo.getDv()[i].getSoluong());;
                String dongia = String.valueOf(balo.getDv()[i].getDongia());;
                String phuongan = String.valueOf(balo.getDv()[i].getPhuongan());;
                

                String Data[] = {tendv, soluong, dongia, phuongan};
                tblModel.addRow(Data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public float max(float a, float b, float c) {
        if (a >= b) {
            if (a > c) {
                return 1;
            } else {
                return 3;
            }
        } else {
            if (b > c) {
                return 2;
            } else {
                return 3;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelChuaDuocThamAn = new javax.swing.JLabel();
        labelGiaTriThamAn = new javax.swing.JLabel();
        labelKLDuThamAn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDoVatThamAn = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelChuaDuocNhanhCan = new javax.swing.JLabel();
        labelGiaTriNhanhCan = new javax.swing.JLabel();
        labelKLDuNhanhCan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDoVatNhanhCan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelChuaDuocQuyHoanhDong = new javax.swing.JLabel();
        labelGiaTriQuyHoanhDong = new javax.swing.JLabel();
        labelKLDuQuyHoanhDong = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDoVatQuyHoanhDong = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ToiUu = new javax.swing.JLabel();
        btnQuayLaij = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tất Cả Thuật Toán");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("So Sánh Tất Cả Thuật Toán");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Thuật Toán tối ưu : ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tham ăn");

        jLabel1.setText("Tống khối lượng balo chứa được :");

        jLabel4.setText("Tổng giá trị :");

        jLabel9.setText("Khối lượng còn dư :");

        labelChuaDuocThamAn.setText("     ");

        labelGiaTriThamAn.setText("     ");

        labelKLDuThamAn.setText("       ");

        tableDoVatThamAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ vật", "Số lượng", "Đơn giá", "Phương án"
            }
        ));
        jScrollPane1.setViewportView(tableDoVatThamAn);

        jLabel5.setText("Tống khối lượng balo chứa được :");

        jLabel6.setText("Tổng giá trị :");

        jLabel11.setText("Khối lượng còn dư :");

        labelChuaDuocNhanhCan.setText("     ");

        labelGiaTriNhanhCan.setText("     ");

        labelKLDuNhanhCan.setText("       ");

        tableDoVatNhanhCan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ vật", "Số lượng", "Đơn giá", "Phương án"
            }
        ));
        jScrollPane2.setViewportView(tableDoVatNhanhCan);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nhánh cận");

        jLabel8.setText("Tổng giá trị :");

        jLabel12.setText("Khối lượng còn dư :");

        labelChuaDuocQuyHoanhDong.setText("     ");

        labelGiaTriQuyHoanhDong.setText("     ");

        labelKLDuQuyHoanhDong.setText("       ");

        tableDoVatQuyHoanhDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ vật", "Số lượng", "Đơn giá", "Phương án"
            }
        ));
        jScrollPane3.setViewportView(tableDoVatQuyHoanhDong);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Quy hoạch động");

        jLabel14.setText("Tống khối lượng balo chứa được :");

        ToiUu.setText("     ");

        btnQuayLaij.setText("Quay Lại");
        btnQuayLaij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(labelGiaTriThamAn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(labelChuaDuocThamAn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(labelKLDuThamAn))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(labelGiaTriNhanhCan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(labelChuaDuocNhanhCan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(labelKLDuNhanhCan))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(labelGiaTriQuyHoanhDong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(labelChuaDuocQuyHoanhDong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(labelKLDuQuyHoanhDong))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnQuayLaij)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ToiUu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ToiUu))
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelChuaDuocThamAn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelGiaTriThamAn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labelKLDuThamAn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelChuaDuocNhanhCan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(labelGiaTriNhanhCan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelKLDuNhanhCan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(labelChuaDuocQuyHoanhDong))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labelGiaTriQuyHoanhDong))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelKLDuQuyHoanhDong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnQuayLaij)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaijActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tat_Ca_Thuat_Toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tat_Ca_Thuat_Toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tat_Ca_Thuat_Toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tat_Ca_Thuat_Toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tat_Ca_Thuat_Toan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ToiUu;
    private javax.swing.JButton btnQuayLaij;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelChuaDuocNhanhCan;
    private javax.swing.JLabel labelChuaDuocQuyHoanhDong;
    private javax.swing.JLabel labelChuaDuocThamAn;
    private javax.swing.JLabel labelGiaTriNhanhCan;
    private javax.swing.JLabel labelGiaTriQuyHoanhDong;
    private javax.swing.JLabel labelGiaTriThamAn;
    private javax.swing.JLabel labelKLDuNhanhCan;
    private javax.swing.JLabel labelKLDuQuyHoanhDong;
    private javax.swing.JLabel labelKLDuThamAn;
    private javax.swing.JTable tableDoVatNhanhCan;
    private javax.swing.JTable tableDoVatQuyHoanhDong;
    private javax.swing.JTable tableDoVatThamAn;
    // End of variables declaration//GEN-END:variables
}
